// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF58AeR7nx3BF_8YKdN0nkkSkpZDeAjfg',
    appId: '1:151414284898:web:b9d7d53162831f5f24673b',
    messagingSenderId: '151414284898',
    projectId: 'esavior-a0437',
    authDomain: 'esavior-a0437.firebaseapp.com',
    storageBucket: 'esavior-a0437.appspot.com',
    measurementId: 'G-RHXHDZJ2DY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYLzSi-XL66Thv9Yrc8ICTmfrMEiAm-xk',
    appId: '1:151414284898:android:defb02ce0152e22824673b',
    messagingSenderId: '151414284898',
    projectId: 'esavior-a0437',
    storageBucket: 'esavior-a0437.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJMA7aIWxg3Za3CL7rA5w-xOblDDi9Wi8',
    appId: '1:151414284898:ios:7db7401493fd858124673b',
    messagingSenderId: '151414284898',
    projectId: 'esavior-a0437',
    storageBucket: 'esavior-a0437.appspot.com',
    iosBundleId: 'com.example.eSaviour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJMA7aIWxg3Za3CL7rA5w-xOblDDi9Wi8',
    appId: '1:151414284898:ios:7db7401493fd858124673b',
    messagingSenderId: '151414284898',
    projectId: 'esavior-a0437',
    storageBucket: 'esavior-a0437.appspot.com',
    iosBundleId: 'com.example.eSaviour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF58AeR7nx3BF_8YKdN0nkkSkpZDeAjfg',
    appId: '1:151414284898:web:1445452e21e32a9424673b',
    messagingSenderId: '151414284898',
    projectId: 'esavior-a0437',
    authDomain: 'esavior-a0437.firebaseapp.com',
    storageBucket: 'esavior-a0437.appspot.com',
    measurementId: 'G-CF7YB7BRQP',
  );
}
